export const guides = [
  {
    slug: 'how-to-make-silk-thread-bangles',
    title: 'How to Make Silk Thread Bangles at Home',
    description: 'A beginner-friendly method for wrapping, decorating and finishing silk thread bangles with commonly used craft materials.',
    category: 'Tutorial',
    readTime: '7 min read',
    datePublished: '2026-06-23',
    dateModified: '2026-07-05',
    image: '/images/generated/banglebychoice-hero.webp',
    collection: '/collections/silk-thread-materials',
    sections: [
      ['Materials to prepare', 'Keep plain bangle bases, silk thread, suitable craft adhesive, scissors and your chosen stones or chain ready before starting. Work on a clean surface and arrange colours in the order you plan to use them.'],
      ['Wrap the bangle evenly', 'Apply adhesive in small sections instead of coating the full bangle. Wrap the thread with steady tension so each turn sits closely beside the previous one without overlapping. Continue until the base is completely covered.'],
      ['Plan the decoration', 'Place stones, chain or hanging elements without glue first. Check the spacing from several angles, then secure each element gradually. Allow the adhesive to cure according to its instructions before wearing or packing the bangle.'],
      ['Finish and store', 'Trim loose thread neatly and check the inner edge for rough spots. Store finished bangles in a dry box away from perfume and moisture so the thread and decorative materials stay clean.'],
    ],
  },
  {
    slug: 'kundan-stones-shapes-and-uses',
    title: 'Kundan Stone Shapes and How to Use Them',
    description: 'Learn how round, teardrop, marquise and geometric Kundan shapes support different jewellery and maggam-work layouts.',
    category: 'Material guide',
    readTime: '6 min read',
    datePublished: '2026-06-23',
    dateModified: '2026-07-05',
    image: '/images/kundan-stones/v-shape-glossy-white_0.webp',
    collection: '/collections/kundan-stones',
    sections: [
      ['Round and oval stones', 'Round and oval Kundan stones are useful for floral centres, repeated borders and balanced traditional patterns. They are easy to combine with smaller accent stones.'],
      ['Teardrop and marquise shapes', 'These elongated shapes naturally suggest petals, leaves and radiating motifs. Use them around a central stone or repeat them along necklace and bangle borders.'],
      ['Square and rectangular stones', 'Geometric stones suit structured layouts, contemporary jewellery and clean border designs. Measure the available space carefully before gluing a repeated row.'],
      ['Choosing adhesive and placement', 'Match the adhesive to both the stone backing and the base material. Test a small area, use only enough adhesive to hold the stone and let the piece cure fully before handling.'],
    ],
  },
  {
    slug: 'jewellery-making-materials-for-beginners',
    title: 'Jewellery-Making Materials for Beginners',
    description: 'A practical starter list covering pliers, cutters, findings, beads, adhesive and storage for first jewellery projects.',
    category: 'Beginner guide',
    readTime: '5 min read',
    datePublished: '2026-06-23',
    dateModified: '2026-07-05',
    image: '/images/jewellery-making/flat-nose-piler_0.webp',
    collection: '/collections/jewellery-making',
    sections: [
      ['Start with essential tools', 'A flat-nose plier, round-nose plier and cutter handle many beginner assembly tasks. Choose tools that feel comfortable in your hand and use them only for their intended materials.'],
      ['Select findings by measurement', 'Before buying hooks, jump rings, pins or connectors, check component thickness, hole size and expected design weight. Small measurement differences can affect assembly.'],
      ['Buy project-sized quantities', 'Plan one or two simple designs and buy the required colours and pack sizes first. This makes it easier to learn which materials you use most before ordering larger quantities.'],
      ['Organise and label supplies', 'Separate findings, stones and tools into labelled containers. Dry, organised storage protects finishes and prevents small components from being lost between projects.'],
    ],
  },
  {
    slug: 'kundan-pack-sizes-10g-50g-100g',
    title: 'How to Choose 10g, 50g and 100g Kundan Packs',
    description: 'Choose a practical Kundan pack size without assuming a fixed piece count, using project scale, stone dimensions and repeat patterns.',
    category: 'Buying guide',
    readTime: '5 min read',
    datePublished: '2026-08-08',
    dateModified: '2026-08-08',
    image: '/images/kundan-stones/6k-eye-shape-glossy-white-premium-product-v6.webp',
    collection: '/collections/kundan-stones',
    sections: [
      ['Why piece count varies', 'Kundan packs are sold by weight, so the number of stones changes with face dimensions, rim, backing and shape. A 10g pack of smaller round stones can contain more pieces than 10g of a larger eye or drop design.'],
      ['When to choose 10g', 'Use a 10g pack to check colour and finish, complete small accents or test a new shape. It is the safer starting point when the final design or matching requirement is not yet confirmed.'],
      ['When to choose 50g or 100g', 'Larger packs suit repeated borders, coordinated sets and multiple pieces using the same design. Estimate the number of repeats in the complete layout and keep a small allowance for placement tests.'],
      ['How to avoid mismatched batches', 'For a project that must use one consistent shade, order the expected quantity together where possible. Compare the real product gallery and contact support before placing a large colour-sensitive order.'],
    ],
  },
  {
    slug: 'choosing-glue-for-kundan-and-bangle-making',
    title: 'Choosing Glue for Kundan and Bangle Making',
    description: 'A practical guide to matching craft adhesive with stone backings, bangle bases, fabric and MDF without over-applying glue.',
    category: 'Material guide',
    readTime: '6 min read',
    datePublished: '2026-08-08',
    dateModified: '2026-08-08',
    image: '/images/silk-thread-materials/b-7000-glue-50ml-premium-product-v6.webp',
    collection: '/collections/silk-thread-materials',
    sections: [
      ['Match both surfaces', 'An adhesive must bond to the decoration backing and the project base. Glass, ceramic, metal, fabric, plastic and MDF can require different handling, so read the adhesive instructions before starting.'],
      ['Test before completing the design', 'Apply a small amount to a spare component or hidden area. Check curing time, flexibility, staining and whether the adhesive remains visible around the edge after drying.'],
      ['Use less adhesive than the stone face', 'Excess glue can spread beyond the rim and collect dust. Apply a controlled amount, position the component once and avoid repeated movement while the bond begins to set.'],
      ['Allow full curing time', 'A surface may feel dry before the adhesive reaches its intended strength. Keep the piece flat and undisturbed for the curing period stated by the adhesive manufacturer before wearing, packing or shipping it.'],
    ],
  },
];

export function getGuide(slug) {
  return guides.find((guide) => guide.slug === slug);
}
